[package]
name = "rdint"
version = "0.1.0"
authors = ["Johan Hidding <j.hidding@esciencecenter.nl>"]

[dependencies]
<<<<<<< HEAD
rand = "0.4"
serde = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
=======
rand = "0.5"
>>>>>>> upstream/master
